### ISSUE TITLE
点击搜索结果，无法进入详情页。系统崩溃

### ISSUE THREAD

**Issue by ShihKing** [0x12fd22c/feedback#1]
**BUG描述**
搜索后点击内容回头弹出无法运行提示，之后应用退出

**操作步骤**
1. Go to 'search'
2. Click on 'Video content'
3. See error

**错误截图**

**设备信息 (please complete the following information):**
 - Device: [e.g. 海美迪Q10]
 - OS: [e.g. Android 7.0]

**Comment by 0x12fd22c** [comment]
@ShihKing 是 Android 7.0 吗？ 我测试没有复现。

**Comment by ShihKing** [comment]
> **BUG描述**
> 搜索后点击内容回头弹出无法运行提示，之后应用退出
> 
> **操作步骤**
> Steps to reproduce the behavior:
> 
> 1. Go to 'search'
> 2. Click on 'Video content'
> 3. See error
> 
> **错误截图**
> If applicable, add screenshots to help explain your problem.
> 
> **设备信息 (please complete the following information):**
> 
> * Device: [e.g. 海美迪Q10]
> * OS: [e.g. Android 7.0]



> @ShihKing 是 Android 7.0 吗？ 我测试没有复现。

是的，我特意检查过了。

**Comment by 0x12fd22c** [comment]
fixed
