### ISSUE TITLE
点击偏好设置应用直接退出

### ISSUE THREAD

**Issue by zjc1994** [0x12fd22c/feedback#2]
**BUG描述**
进入应用，然后点击偏好设置直接退出应用

**操作步骤**
1. Go to 'dogeBox'
2. Click on 'setting'

**错误截图**

**设备信息 (please complete the following information):**
 - Device: [e.g. MiboxS 国际版 ]
 - OS: [e.g. Android 8.0]

**Comment by 0x12fd22c** [comment]
@zjc1994 已修复，下个版本验证。
